### ISSUE TITLE
[BUG][8.0][cenit_recipe_and_grocery_list_api_v_partner] Field summary too long

### ISSUE THREAD

**Issue by andhit-r** [cenit-io/odoo-integrations#34]
Exception raise when create new db.

INSERT INTO ir_module_module                 (author, website, name, shortdesc, description,                     category_id, auto_install, state, web, license, application, icon, sequence, summary)                 VALUES ('Cenit IO', 'https://cenit.io', 'cenit_recipe_and_grocery_list_api_v_partner', 'Recipe_and_grocery_list_api_v_partner Integration', '
        Odoo - Recipe_and_grocery_list_api_v_partner integration via Cenit IO
    ', 5, false, 'uninstalled', false, 'AGPL-3', false, '/cenit_recipe_and_grocery_list_api_v_partner/static/description/icon.png', 100, '#Documentation

This is the documentation for the partner endpoint of the BigOven Recipe and Grocery List API.

The update brings with it Swagger-based documentation. [Swagger](http://swagger.io) is an emerging standard for describing REST-based APIs, and with this Swagger-compliant endpoint (above), you can make ready-to-go interface libraries for your code via [swagger-codegen](https://github.com/swagger-api/swagger-codegen). For instance, it''s easy to generate libraries for Node.js, Java, Ruby, ASP.NET MVC, jQuery, php and more!

You can also try out the endpoint calls with your own api_key right here on this page. Be sure to enter your api_key above to use the "Try it out!" buttons on this page.

##Start Here

Developers new to the BigOven API should start with this version, not with the legacy API. We''ll be making improvements to this API over time, and doing only bug fixes on the v1 API.

To pretend you''re a BigOven user (for instance, to get your recently viewed recipes or your grocery list), you need to pass in Basic Authentication information in the header, just as with the v1 API. We do now require that you make all calls via https. You need to pass your api_key in with every call, though this can now be done on the header (send a request header "X-BigOven-API-Key" set to your api_key value, e.g., Request["X-BigOven-API-Key"]="your-key-here".)

##Migration Notes

For existing partners, we encourage you to [migrate](http://api2.bigoven.com), and while at this writing we have no hard-and-fast termination date for the v1 API, we strongly prefer that you migrate by January 1, 2017. While the changes aren''t overly complex, there are several breaking changes, including refactoring of recipe search and results and removal of support for XML. This is not a simply plug-and-play replacement to the v1 API. With respect to an exclusive focus on JSON, the world has spoken, and it prefers JSON for REST-based API''s. We''ve taken numerous steps to refactor the API to make it more REST-compliant. Note that this v2 API will be the preferred API from this point onward, so we encourage developers to migrate to this new format. We have put together some [migration notes](/web/documentation/migration-to-v2) that we encourage you to read carefully.

##Photos

See our [photos documentation](http://api2.bigoven.com/web/documentation/recipe-images). 

For more information on usage of this API, including features, pricing, rate limits, terms and conditions, please visit the [BigOven API website](http://api2.bigoven.com).') RETURNING id
Traceback (most recent call last):
  File "/home/andhit_r/odoo8/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
DataError: value too long for type character varying(256)

2016-12-23 12:01:50,378 6241 CRITICAL ? openerp.service.server: Failed to initialize database `cenit-test-1`.
Traceback (most recent call last):
  File "/home/andhit_r/odoo8/odoo/openerp/service/server.py", line 937, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/andhit_r/odoo8/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/andhit_r/odoo8/odoo/openerp/modules/loading.py", line 273, in load_modules
    openerp.modules.db.initialize(cr)
  File "/home/andhit_r/odoo8/odoo/openerp/modules/db.py", line 86, in initialize
    info['sequence'], info['summary']))
  File "/home/andhit_r/odoo8/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/andhit_r/odoo8/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
DataError: value too long for type character varying(256)

**Comment by sanchojaf** [comment]
Hi @andhit-r  the issue was fixed, thanks for your feedback
